db:
  image: mysql:5.7.21
  environment:
    MYSQL_ROOT_PASSWORD: strong-passw0rd
    MYSQL_DATABASE: myapp
    MYSQL_USER: myapp_user
    MYSQL_PASSWORD: myapp_pass
  volumes:
    - "./mysql:/docker-entrypoint-initdb.d"
  ports:
    - 3306:3306

keycloak:
  image: jboss/keycloak
  volumes:
    - "./realm-export.json:/tmp/realm-export.json"
  environment:
    KEYCLOAK_USER: root
    KEYCLOAK_PASSWORD: root
    KEYCLOAK_IMPORT: /tmp/realm-export.json
  ports: 
    - "8081:8080"

app_1:
  image: jabley/stateless-tomcat:standalone
  environment:
      CATALINA_OPTS : >
        -Dconnector.scheme=http
        -Dconnector.proxy.port=8081
        -Dconnector.secure=false
        -Dserver.port=8081
  ports:
    - "8080:8080"
  links:
    - db
    - keycloak
  volumes:
    - "./lib:/usr/local/tomcat/lib"

app_2:
  image: jabley/stateless-tomcat:standalone
  ports:
    - "8082:8080"
  links:
    - db
    - keycloak
  volumes:
    - "./lib:/usr/local/tomcat/lib"

app_3:
  image: jabley/stateless-tomcat:standalone
  ports:
    - "8083:8080"
  links:
    - db
    - keycloak
  volumes:
    - "./lib:/usr/local/tomcat/lib"
    
# haproxy container that automatically creates a load balancer / reverse proxy across the 3 instances of the app
haproxy:
  image: haproxy:1.8.4
  ports:
    - "81:80"
  volumes:
    - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
  links:
    - app_1
    - app_2
    - app_3
    - keycloak
