app_1:
  image: jabley/stateless-tomcat:standalone
  ports:
    - "8081:8080"

app_2:
  image: jabley/stateless-tomcat:standalone
  ports:
    - "8082:8080"

app_3:
  image: jabley/stateless-tomcat:standalone
  ports:
    - "8083:8080"
    
# haproxy container that automatically creates a load balancer / reverse proxy across the 3 instances of the app
haproxy:
  image: haproxy:1.8.4
  ports:
    - "81:80"
  volumes:
    - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
  links:
    - app_1
    - app_2
    - app_3
